M48
; DRILL file {KiCad 9.0.2} date 2025-10-26T22:21:00-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-26T22:21:00-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X104.96Y-125.635
X110.04Y-124.619
X110.04Y-126.651
M30
